name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build code
        uses: docker://longfangsong/lab:v5
        with:
          args: -f ./student.yaml -o ./student

      - name: Build and release docker image
        working-directory: ./student
        run: |
          docker build . -t auto-api-example
          docker tag auto-api-example ${{ secrets.DOCKER_USERNAME }}/auto-api-example:latest
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/auto-api-example
